/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 dualshock.glb --transform 
Files: dualshock.glb [8.61MB] > D:\GLTF\dualshock-transformed.glb [4.4MB] (49%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dualshock-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.UpperBody.geometry} material={materials.UpperBodyC} position={[0.028, 0.082, -0.176]} rotation={[1.049, -0.581, -2.656]} scale={-0.06} />
      <mesh geometry={nodes.UnderBody.geometry} material={materials.UnderBodyC} position={[0.028, 0.082, -0.176]} rotation={[1.049, -0.581, -2.656]} scale={-0.06} />
      <mesh geometry={nodes.RL.geometry} material={materials.RLC} position={[0.028, 0.082, -0.176]} rotation={[1.049, -0.581, -2.656]} scale={-0.06} />
      <mesh geometry={nodes.smallStuff.geometry} material={materials.smallStuffC} position={[0.028, 0.082, -0.176]} rotation={[1.049, -0.581, -2.656]} scale={-0.06} />
      <mesh geometry={nodes.blackBottom.geometry} material={materials.blackBottomC} position={[0.028, 0.082, -0.176]} rotation={[1.049, -0.581, -2.656]} scale={-0.06} />
      <mesh geometry={nodes.BlueStripe.geometry} material={materials.BlueStripeC} position={[0.028, 0.082, -0.176]} rotation={[1.049, -0.581, -2.656]} scale={-0.06} />
      <mesh geometry={nodes.pad.geometry} material={materials.padC} position={[0.028, 0.082, -0.176]} rotation={[1.049, -0.581, -2.656]} scale={-0.06} />
      <mesh geometry={nodes.Analogue.geometry} material={materials.AnalogueC} position={[0.028, 0.082, -0.176]} rotation={[1.049, -0.581, -2.656]} scale={-0.06} />
    </group>
  )
}

useGLTF.preload('/dualshock-transformed.glb')
