/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 laptop.glb --transform 
Files: laptop.glb [1.98MB] > D:\GLTF\New folder (2)\laptop-transformed.glb [130.32KB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/laptop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.screen.geometry} material={materials.screen} position={[0, -0.09, 0.048]} rotation={[1.942, 0.011, 2.224]} scale={0.154} >
        {snap.isFullTexture && (
          <>
            <Decal
              position={[0, -1, -0.8]}
              rotation={[1.5, 0, 0]}
              scale={4.6}
              map={fullTexture}>
              <meshStandardMaterial
                map={fullTexture}
                polygonOffset
                polygonOffsetFactor={-1} />
            </Decal>
          </>
        )}
        {snap.isLogoTexture && (
          <Decal
            position={[0, -1, -1]}
            rotation={[1.5, 0, 3.14]}
            scale={0.7} map={logoTexture}
            depthTest={false}
            depthWrite={true} />
        )}
      </mesh>
      <mesh geometry={nodes.body.geometry} material={materials.body} position={[0, -0.09, 0.048]} rotation={[1.942, 0.011, 2.224]} scale={0.154} />
      <mesh geometry={nodes.webcam.geometry} material={materials.webcam} position={[0, -0.09, 0.048]} rotation={[1.942, 0.011, 2.224]} scale={0.154} />
      <group position={[0, -0.09, 0.048]} rotation={[1.942, 0.011, 2.224]} scale={0.154}>
        <mesh geometry={nodes.kayboard.geometry} material={materials.keycaps} />
        <mesh geometry={nodes.kayboard_1.geometry} material={materials.glow} />
      </group>
    </group>
  )
}

useGLTF.preload('/laptop-transformed.glb')
