/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 midi.glb --transform 
Files: midi.glb [8.73MB] > D:\Web Development\Projects\3d-showcase-web\public\midi-transformed.glb [1.55MB] (82%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/midi-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.base.geometry} material={materials.base} position={[0.013, 0.023, 0.028]} rotation={[0.755, 0.644, -0.176]} scale={1.409} >
        {snap.isFullTexture && (
          <>
            <Decal
              position={[0, 0, 0]}
              rotation={[1.2, 0, 0]}
              scale={0.526}
              map={fullTexture}>
              <meshStandardMaterial
                map={fullTexture}
                polygonOffset
                polygonOffsetFactor={-1} />
            </Decal>
          </>
        )}
        {snap.isLogoTexture && (
          <Decal
            position={[0.247, 0.021, -0.075]}
            rotation={[1.5, 3.1, -3]}
            scale={0.023} map={logoTexture}
            depthTest={false}
            depthWrite={true} />
        )}
      </mesh>
      <mesh geometry={nodes.keys.geometry} material={materials.keys} position={[0.021, 0.068, 0.062]} rotation={[0.755, 0.644, -0.176]} scale={[0.373, 0.032, 0.127]} />
      <mesh geometry={nodes.keysBlack.geometry} material={materials.keysBlack} position={[0.191, 0.124, -0.191]} rotation={[0.755, 0.644, -0.176]} scale={0.009} />
      <mesh geometry={nodes.buttons.geometry} material={materials.buttons} position={[0.013, 0.023, 0.028]} rotation={[0.755, 0.644, -0.176]} scale={1.409} />
      <mesh geometry={nodes.buttons2.geometry} material={materials.buttons2} position={[0.013, 0.023, 0.028]} rotation={[0.755, 0.644, -0.176]} scale={1.409} />
      <mesh geometry={nodes.cube.geometry} material={materials.cube} position={[0.013, 0.023, 0.028]} rotation={[0.755, 0.644, -0.176]} scale={1.409} />
    </group>
  )
}

useGLTF.preload('/midi-transformed.glb')
